uber-go/guide

- style.md
Consistent with our guidance to avoid providing public functions that
accept private types and to give library authors full latitude to change
the underlying implementation of functional options, we now suggest
using a public Option interface with a private method.
We have also learned not to mix the words option and configuration in
the same context. An option is a function parameter to override
behavior. Configuration is parsed from files and frequently maps to
options.
> Clarify guidance for option functions.

- style.md
We had a leftover code sample that set up a zero-value mutex and locked
and unlocked it right after the bad-good comparison.
> Zero-value mutexes: Remove leftover code sample

- style.md
This fixes a typo in the functional options code sample. When Option is
an interface, we need to `.apply` it.
Resolves #13
> Functional Options: Apply the interface method

- style.md
This was a bit confusing to digest at first. I think at a minimum, the index value should be consistent with the previous line, but it might be a little more clear to not use a `map` here.
We say at the top of the section:
```
Methods with value receivers can be called on pointers as well as values.
```
but the given example shows that only the `Read()` method works. Not the pointer receiver.
I honestly wasn't aware that being the value inside of a`map` type changed this behavior. I was expecting both to compile, because you _should_ be able to use type `S{}` with both value and pointer receivers.
I think it would be more clear to say
```go
type S struct {
data string
}
func (s S) Read() string {
return s.data
}
func (s *S) Write(str string) {
s.data = str
}
sVals := S{"A"}
// You can …
```
> Change index value from 0 to 1

- style.md
As pointed out in #19, the second Good example for "Reduce Scope of
Variables" leaks an open file descriptor if `io.WriteString` fails.
Further, both sets of examples are manually closing files instead of
using `defer` as pointed out elsewhere in the guide.
As these examples just need a pair of functions, one returning just an
error, another returning a value and an error, I've switched them to
using `ioutil.ReadFile`, `ioutil.WriteFile`, and a plausible
`Config.Decode([]byte) error` method on a `cfg` variable assumed to be
in-scope.
Resolves #19
> Reduce Scope: Fix FD leak

- style.md
More explicitly call out that mutexes should only be embedded
in unexported types.
Related to #23.
> Mutexes should only be embedded in unexported

- README.md
This adds a translations section to the README with a link to the only
translation repository that we know of at this time.
Resolves #31
> README: Add translations section

- style.md
Related to #23.
Also clarify that any access to the snapshot would be racy to make it clear there's no safe
way to access the snapshot.
Supercedes #21.
> Remove embedded mutex in exportd type

- style.md
This changes the Initializing Maps guidance proposed in #55 to...
- provide the guidance first
- include examples for both cases
- provide the rules last
This drops the mention of rvalue as well because readers unfamiliar
with C++ will find that confusing.
> Initializing Maps: Refactor

- CHANGELOG.md
- style.md
Per #74, this changes the recommendation for functional options to
suggest manual interface implementations instead of closures.
To make the example more demonstrative, I had to add a new option which
hurt the overall readability of the side-by-side comparison. This lead
to a minor reorganization: side-by-side includes user-facing API and
usage only, and implementation is demonstrated separately in its own
paragraph.
Resolves #74
> Functional Options: Don't recommend closures

- style.md
This PR will add the missing `open` function parameter in the Error section examples. If no parameter is used, the program will not run and we should see an error message similar to this: 
```
not enough arguments in call to open
```
> Fix missing open function parameter

- style.md
opts.Logger = l.Log should be opts.logger = l.Log
> opts.Logger = l.Log should be opts.logger = l.Log

- style.md
This change introduces a section about avoiding the use of type embedding because it limits the evolution of the container type.
> Avoid embedding types in public structs

- CHANGELOG.md
- style.md
This adds a new section recommending use of the time package when
dealing with time. It ports over recommendations for `time.Duration` and
`time.Time` from the internal guide, explaining that time is complicated
as rationale.
> Guideline: Use "time" to handle time

- CHANGELOG.md
- style.md
This adds advice on verifying interface compliance with
`var _ Interface = (*Foo)(nil)`.
As part of this guideline, we have to cover that if the receiver is on
the value type, the right side should be the zero value. Because of
that, the guideline is placed right before the section where we talk
about receiver types for interfaces.
Resovles #25
---
[Preview](https://github.com/uber-go/guide/blob/abg/interface-compliance/style.md#verify-interface-compliance)
> Guidelines: Verify Interface Compliance

- style.md
To fix #88 , add type to enum group.
> Fix missing type in example for naked parameters

- style.md
> Add guidance to avoid using built-in names

- style.md
Per @prashantv's [feedback](https://github.com/uber-go/guide/pull/79#pullrequestreview-380021958) on #79:
> Suggestion: Rather than having 2 separate topics with similar guidelines, what if this was one guideline with sub-headings for maps vs slices.
> 
> We can have the common reasons, then have type-specific examples + reasons in the sub-headings.
This also expands a bit more on map allocations at initialization time.
> Combine capacity guidance for maps and slices

- style.md
Initializing Maps got a broken link when specifying map sizes got refactored to specifying container sizes.
Fixes #99
> Fix a link to Specifying Map Capacity Hints

- style.md
In our example, we `panic` in `main` instead of the function `foo`. The
point that this was demonstrating was that the caller of the function
has the choice of panicking rather than `foo` itself.
Unfortunately, this causes confusion for readers modeling their `main()`
after this code, because the "good" example still panics.
This reduces confusion here by having `main` handle the `error` with an
`os.Exit`.
Note that this moves argument handling into `foo` because placing it in
`main` is not very testable.
> Don't Panic: Remove main panic

- style.md
> don't use interface pointer

- style.md
Title case the link for Go Common Mistakes guide to match format of
other links.
> Go Common Mistakes: Title case

- CHANGELOG.md
- style.md
This adds a new Struct Initialization section, moving the old "use field
names" and "initializing struct references" guidelines under it.
In the new section, based on #109, this adds the following new sections:
- Omit zero value fields
- Use var for zero value structs
Each commit is individually reviewable.
Preview: https://github.com/uber-go/guide/blob/abg/struct-init/style.md#initializing-structs
Resolves #109
> Additional guidance on struct initialization

- CHANGELOG.md
- style.md
In #66, we discussed advising at most one `log.Fatal` per program. This
can be split into two pieces of guidance:
1. exit only in main
2. exit only once
Applying to both, `os.Exit` and `log.Fatal`.
This adds (1) as a guidance to the style guide, and (2) as an optional
"upgrade" for extra points.
At minimum, (1) gives us easy-to-follow control flow and testability
outside main. If readers are sold on that, (2) gives us testable
`main()` logic.
Preview: https://github.com/uber-go/guide/blob/abg/exit-once/style.md#exit-in-main
Resolves #66
> Add guidance on exiting

- style.md
Our guidance for mutexes suggested that it was okay to embed mutexes in
structs if the struct was unexported. This was left as an allowance for
"if you really want to do it, this is the only time it's okay", but that
nuance doesn't translate well to the style guide.
Advise against embedding mutexes completely to resolve any confusion
here.
Resolves #127
> Mutexes: Advise against embedding

- CHANGELOG.md
- style.md
Per #122, this advises a **soft** line length limit of 99 characters
and explicitly states that it's okay to exceed the limit.
Resolves #122
> style: 99 character soft limit on line length

- CHANGELOG.md
- style.md
This PR updates the guidance we have for errors to reflect best practices since
Go 1.13's error APIs. The high-level overview of the guidance is:
- use `errors.New` for static strings,
exporting a `var` if it needs to be matched
- declare a custom error type if it needs to be matched
- use `fmt.Errorf` for dynamic strings if it does not need to be matched
- use `fmt.Errorf` with `%w` when wrapping if the wrapped error needs to be
matched
- name top-level error variables `errFoo` or `ErrFoo`
- name error types `FooError`
Resolves #132, #8
Ref GO-1014
---
[Preview](https://github.com/uber-go/guide/blob/error-wrapping/style.md)
> errors: Update for errors.Is/As

- style.md
This makes the following changes to the error types and wrapping sections:
- Supporting `errors.Is` vs `errors.As` is an "or", not an "and"
because you're typically exposing either a `var` (for `errors.Is`)
or a type (for `errors.As`).
- Use pointer receivers in sample error implementations.
The equality semantics of pointer-based implementations
are usually what most people want.
We don't explicitly require that people use pointer-based receivers.
- Clarify picking between `%v` and `%w` further.
Use of `%w` doesn't automatically make it part of your public API,
but there is risk in users relying on it.
So if the wrapped error is a known type/value,
we want authors to be intentional about using `%w` or `%v` there.
Thanks to @peterbourgon for the review of #134 pointing out these issues.
> Error types/wrapping updates from #134

- style.md
Close `<td>` or `<tr>`, this should help with `mdx` compatibility.
Also add missed newline.
> Fix table tags

- style.md
The instructions were contradictory:
- description say "embedded structs such as mutexes"
- later on, examples lists mutexes as something that shouldn't be embedded.
Let's clarify.
> Clarify mutexes should not be embedded

- style.md
Previously, grouping guidance as it relates to variables was ambiguous, and in some cases could lead folks to think that variables should only be grouped if they're of the same type or are directly related.
Since we group all consecutive variable declarations in practice, regardless of whether they're related by semantics or type, this clarifies the guidance by adding an exception for variables so that they are grouped more liberally.
> Clarify guidance for grouping consecutive variable declarations

- CHANGELOG.md
- style.md
Updating public guide with previously discussed (internally) proposal on tagging struct fields that are being marshalled into JSON/YAML/etc
> Added guidance on field tags in marshalled structs

- README.md
This simply adds a link to a French version of this very useful style guide.
Thanks.
> Add link to French translation

- CHANGELOG.md
- style.md
This is mostly an RFC based on some internal discussions.
In general, we prefer for goroutines to have well-managed lifecycles.
No uncontrolled background work that cannot be stopped.
This change tries to distill some of the guidance around it into a style
guide entry.
It's not super comprehensive, but it tries to cover some of the guiding
principles.
Rendered: https://github.com/uber-go/guide/blob/goroutines/style.md#dont-fire-and-forget-goroutines
> Add guidance on goroutine lifecycle management

- style.md
I just noticed that I should open an issue before making a PR. Really sorry about not noticing it, and I have opened #165 for tracking this PR!
---
markdownlint is a static analysis tool with a library of rules to enforce standards and consistency for Markdown files. [^1]
This commit removes redundant spaces, unused references, indent mistakes, etc. from this document according to the report from `markdownlint`.
Note that I disable `MD033` (no-inline-html) as it is necessary for side-by-side code samples.
[^1]: https://github.com/DavidAnson/markdownlint
> style: Lint with markdownlint

- CHANGELOG.md
- src/interface-receiver.md
- style.md
The guidance in this section was a bit confusing
because it didn't quite explain why we could only call Read, not Write,
on the values stored in the map.
Resolves #163
> interface-receiver: Clarify why value receiver can be called

- Makefile
The lint target currently fails silently in CI
because of the use of `[[`.
/bin/sh: 2: [[: not found
This is because `[[` is a built-in in bash, not in sh.
sh only has `[`.
Fix this by setting the shell to bash in make.
> make: Fix lint target

- Makefile
Because `GOBIN` is set conditionally, its value might not be `$makefile_dir/bin` - use the value of the variable instead of hardcoding `bin/`.
> make: Fix stitchmd path

- .github/workflows/ci.yml
The operation failed in #174 because the PR was made from a fork. Looking at the [documentation for git-auto-commit-acton](https://github.com/stefanzweifel/git-auto-commit-action), it's possible to support this for forks as well if we use the `pull_request_target` event (which runs in the context of the base branch), and check out the PR repository (which may be a fork). See also https://github.com/stefanzweifel/git-auto-commit-action#use-in-forks-from-public-repositories.
> ci/stitchmd: Support updating PRs from forks

- .github/workflows/ci.yml
#181 tried to fix support for PRs from forks
by changing the event to pull_request_target.
However, it did not update the check we do on github.event_name later
to decide whether we're in check mode or write.
This updates the job to fix the event name match.
> ci/stitchmd: Fix write mode for PRs

- .github/workflows/ci.yml
Auto-commit to PRs only if the event is pull_request_target not pull_request, because we've changed the event we dispatch on.
(I missed this in the prior two PRs. 😞 )
> ci/stitchmd: Run git-auto-commit-action on pull_request_target

- src/test-table.md
- style.md
The tables added in #174 are a bit wide and hard to fit on smaller screens.
By changing the `\t` to `  `, and splitting a line, we can reduce this width.
> visual fix: reduce width and replace tabs

- src/exit-once.md
- style.md
Clarify that the example of using `run()` and `log.Fatal` isn't intended
to be prescriptive.
Provide samples of using `os.Exit` directly, using different exit codes,
and clarify that there's flexibility here on how everything is set up.
Refs #189
> exit-once: Clarify that `run()` ins't prescriptive

- src/SUMMARY.md
- src/string-byte-slice.md
- style.md
Currently "Avoid string-to-byte conversion" sounds like we should avoid it at all, but this paragraph means else
> Fix header for string-byte-slice

- src/atomic.md
- src/builtin-name.md
- src/embed-public.md
- src/error-type.md
- src/exit-main.md
- src/function-name.md
- src/interface-receiver.md
- src/intro.md
- src/lint.md
- src/package-name.md
- src/printf-name.md
- src/string-escape.md
- src/struct-embed.md
- src/struct-field-key.md
- src/struct-zero.md
- src/test-table.md
- src/time.md
- src/type-assert.md
- src/var-decl.md
- style.md
This PR updates,
- links from golang.org/ to go.dev/
- github.com/golang/go/wiki links to go.dev/wiki
- additionally, some markdown links to a section have been replaced with their corresponding .md files
Resolves [#260](https://github.com/uber-go/guide/issues/206)
> chore: Update external Go links

- src/var-scope.md
- style.md
See https://github.com/uber-go/guide/issues/216 for more information.
This is just a draft, and more to start discussion to understand what the correct guidance here is.
> give guidance to reduce scope of constants

- src/import-alias.md
- style.md
This update refines the BAD example in `import-alias.md` to better illustrate improper usage of import aliases, making it easier for readers to understand and learn from the mistake.
> Update BAD Example in `import-alias.md`

- README.md
This PR adds a link to the Bahasa Indonesia translation of the Uber Go Style Guide to the list of available translations in the README.
It aims to help Indonesian developers understand and adopt this guide more easily.
> docs(README): add Indonesian translation to the translation link list
