CHANGELOG.md
style.md

Recommend keeping error contexts succinct.

Succinct error contexts

---

style.md

code sample missing a block symbol

---

README.md

I add the link for my translation work. translation itself will be done by 20th of Oct, 2019.

add link for korean translation

---

README.md

I think it's better to use the local language tags

Chinese to local language

---

README.md

This adds the English names of translations to the README.

translations: Include English names

---

README.md

I translated this great guide into Japanese.
so I want you to add link to my work.

Add link to Japanese

---

style.md

Add consistency section

---

README.md
style.md

Add guidance for initializing maps

---

README.md

I have provided a Spanish translation and I hope it can be included. :)

Included Spanish translations on the list.

---

CHANGELOG.md

This updates the changelog based on changes made in those two PRs.

CHANGELOG: Updates for #55 and #58

---

README.md

Hello again 👋! Add link to Russian translation please.
I almost finished it. Rest couple moments with meaning in some parts that left untranslated.

README: Add Russian translation

---

CHANGELOG.md

This adds an entry to the changelog for #84.

CHANGELOG: Update for #84

---

style.md

Expand on embedding

---

style.md

Add guidance on avoiding init()

---

.golangci.yml
style.md

Add Linting section

---

style.md

Signed-off-by: Yang Xuan <jumpthepig@gmail.com>
#115

fix go common mistakes guide link

---

style.md

Hello!
I suggest you use errors.Is in good example

refactor: Added errors is

---

style.md

refactor: Changed verb

---

style.md

Changed const name style from snake_casse to MixedCase
https://talks.golang.org/2014/names.slide#5

refactor: change snake_casse to MixedCase

---

README.md

This PR adds a link to a Ukrainian translation of this useful style guide.
Thanks.

Add link to Ukrainian translation

---

README.md

Add link to Portuguese PT-BR translation
